version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=infoOskey
      - MYSQL_DATABASE=infoos
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=infoOskey
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=mysql://admin:infoOskey@db:3306/infoos
    volumes:
      - ./:/app
volumes:
  db_data:

  