services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - URL_DATABASE=${URL_DATABASE}
    restart: always
  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
