services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - JWT_SECRET=jwtTokenSecret
      - URL_DATABASE=admin:infoOskey@tcp(db:3306)/infoos?charset=utf8mb4&parseTime=True&loc=Local
    restart: always
  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=infoOskey
      - MYSQL_DATABASE=infoos
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=infoOskey
    ports:
      - 3306:3306
    


