services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=infoOskey
      - MYSQL_DATABASE=infoos
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=infoOskey
    ports:
      - 3306:3306
