services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - 8080:8080
    restart: always
  db:
    image: mysql:latest
    container_name: db
    ports:
      - 3306:3306
    restart: always
