# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: trust repo
      run: git config --global --add safe.directory /home/api-info-os/actions-runner/_work/api-info-os/api-info-os

    - name: pull
      run: git pull

    - name: docker
      run: docker compose up -d --build
