# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  update:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: trust repo
      run: git config --global --add safe.directory /home/api-info-os/actions-runner/_work/api-info-os/api-info-os

    - name: pull
      run: git pull

  deploy:
    runs-on: self-hosted
    needs: update
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Create .env file
      run: |
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "URL_DATABASE=${{ secrets.URL_DATABASE }}" >> .env
        echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> .env
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> .env
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> .env
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> .env

    - name: Deploy using Docker Compose
      run: |
        docker compose down
        docker compose --env-file .env up -d --build